const fs=require('fs');
const path=require('path');
const root=process.argv[2]||'app';
const file=path.join(root,'resources/app/gyomuon.js');
const text=fs.readFileSync(file,'utf8');
function findFunction(text,name){const re=new RegExp('function\\s+'+name+'\\s*\\(','g');const m=re.exec(text);if(!m)return null;const open=text.indexOf('{',m.index);let d=1,q=null,cmt=null;for(let i=open+1;i<text.length;i++){const c=text[i],n=text[i+1];if(cmt==='line'){if(c==='\n')cmt=null;continue;}if(cmt==='block'){if(c==='*'&&n==='/'){cmt=null;i++;}continue;}if(q){if(c==='\\'){i++;continue;}if(c===q)q=null;continue;}if(c==='/'&&n==='/'){cmt='line';i++;continue;}if(c==='/'&&n==='*'){cmt='block';i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')d++;else if(c==='}'&&--d===0)return text.slice(m.index,i+1);}return null;}
const body=findFunction(text,'bindPage');if(!body)throw new Error('bindPage not found');
const lines=body.split(/\r?\n/).map((line,i)=>({line:i+1,text:line.trim()})).filter(x=>x.text);
const bindings=[];
for(const row of lines){const s=row.text;if(!(/addEventListener\s*\(|\.(onclick|onchange|oninput|onsubmit|onkeydown|onkeyup)\s*=/.test(s)))continue;let target='unknown',event='direct';let m=s.match(/\$\((['"`])([^'"`]+)\1\)\?*\.addEventListener\((['"])([^'"]+)\3/);if(m){target=m[2];event=m[4];}else if((m=s.match(/querySelector\((['"`])([^'"`]+)\1\)\?*\.addEventListener\((['"])([^'"]+)\3/))){target=m[2];event=m[4];}else if((m=s.match(/querySelectorAll\((['"`])([^'"`]+)\1\).*addEventListener\((['"])([^'"]+)\3/))){target=m[2];event=m[4];}else if((m=s.match(/getElementById\((['"`])([^'"`]+)\1\).*addEventListener\((['"])([^'"]+)\3/))){target='#'+m[2];event=m[4];}else if((m=s.match(/\.(onclick|onchange|oninput|onsubmit|onkeydown|onkeyup)\s*=/))){event=m[1].slice(2);const t=s.slice(0,m.index).trim();target=t.slice(-120);}const recreated=/host\.querySelector|host\.querySelectorAll|\[data-|render\(|showEmbeddedDashboard|innerHTML/.test(s);const guarded=/dataset\.bound|\.dataset\.[A-Za-z0-9_]+Bound|if\([^)]*!.*dataset/.test(s);const globalish=/^#|settings|scoreQuery|admissionQuery|fiveGrade|officialAttendance|lateAttendance/.test(target);let classification='REVIEW';if(guarded)classification='ALREADY_GUARDED';else if(globalish&&!recreated)classification='ONE_TIME_CANDIDATE';else if(recreated)classification='DYNAMIC_KEEP_OR_DELEGATE';bindings.push({line:row.line,target,event,classification,source:s.slice(0,500)});}
const key=x=>`${x.target}::${x.event}`;const groups={};for(const b of bindings)(groups[key(b)]??=[]).push(b);const duplicates=Object.entries(groups).filter(([,v])=>v.length>1).map(([k,v])=>({key:k,count:v.length,classifications:[...new Set(v.map(x=>x.classification))],lines:v.map(x=>x.line)})).sort((a,b)=>b.count-a.count);
const summary={total:bindings.length,oneTime:bindings.filter(x=>x.classification==='ONE_TIME_CANDIDATE').length,dynamic:bindings.filter(x=>x.classification==='DYNAMIC_KEEP_OR_DELEGATE').length,guarded:bindings.filter(x=>x.classification==='ALREADY_GUARDED').length,review:bindings.filter(x=>x.classification==='REVIEW').length,duplicateGroups:duplicates.length};
fs.mkdirSync('performance-classification-output',{recursive:true});fs.writeFileSync('performance-classification-output/bindpage-classification.json',JSON.stringify({summary,duplicates,bindings},null,2));let md=`# bindPage performance classification\n\n- total bindings: ${summary.total}\n- one-time candidates: ${summary.oneTime}\n- dynamic keep/delegate: ${summary.dynamic}\n- already guarded: ${summary.guarded}\n- review: ${summary.review}\n- duplicate target/event groups: ${summary.duplicateGroups}\n\n## One-time candidates\n`;for(const b of bindings.filter(x=>x.classification==='ONE_TIME_CANDIDATE'))md+=`- L${b.line} ${b.event} ${b.target}\n`;md+='\n## Duplicate groups\n';for(const d of duplicates)md+=`- ${d.count}x ${d.key} lines ${d.lines.join(', ')}\n`;fs.writeFileSync('performance-classification-output/BINDPAGE-CLASSIFICATION.md',md);console.log(JSON.stringify(summary,null,2));